### PR TITLE
Booking-dei-landing page modified

### PR DESCRIPTION
**Pull request by Bishal-Arman**
I have changed the text, logo and image and theme color.

### CODE REVIEW

**Comment by Bishal-Arman** [comment]
I worked on images, content and logo .Next I will work on color
bookingdei_landing_page

**Review by annur-nifty — COMMENTED** [review]
Good

**Comment by Bishal-Arman** [comment]
#Feat:Change theme color, some image change in More_features  and logo cahnge in login and registration page

theme-change_bookingLanding page

**Review by annur-nifty — COMMENTED** [review]
Great work

**Pull request closed without merging**
