### PR TITLE
All images and two sections data changed in the home page

### PR DESCRIPTION
**Pull request by opu183059**

### CODE REVIEW

**Comment by opu183059** [comment]
**Full page Screenshot**

screencapture-localhost-3008-en-2023-10-30-17_37_05

**Review by annur-nifty — COMMENTED** [review]
Awesome it works fine

**Comment by opu183059** [comment]
New section added @annur-nifty 

Advertisement

**Review by annur-nifty — COMMENTED** [review]
Good, works as well

**Review by ahmad-ml — APPROVED** [review]

**Review by ahmad-ml — APPROVED** [review]

**Pull request merged**
